/**
 * Desktop, Terminal, and Browser DOM Tool Descriptors
 *
 * These are the main computer use tools from register-tools.ts
 */

import type { ToolDescriptor } from './types'

export const desktopDescriptors: ToolDescriptor[] = [
  // Desktop observation tools
  {
    canonicalName: 'desktop_get_capabilities',
    displayName: 'Desktop Get Capabilities',
    summary: 'Get system capabilities, preflight checks, and policy configuration. Returns executor type, permissions, display info, and coordinate space details.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_observe_windows',
    displayName: 'Desktop Observe Windows',
    summary: 'List visible windows with optional app name filter. Returns window titles, bounds, and PIDs.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_screenshot',
    displayName: 'Desktop Screenshot',
    summary: 'Capture a screenshot of the current display. Returns the image in base64 format with optional metadata label.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },

  // Desktop interaction tools
  {
    canonicalName: 'desktop_open_app',
    displayName: 'Desktop Open App',
    summary: 'Open an application. Requires the app to be in COMPUTER_USE_OPENABLE_APPS configuration.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'desktop_focus_app',
    displayName: 'Desktop Focus App',
    summary: 'Focus an application window. Requires the app to be in COMPUTER_USE_OPENABLE_APPS configuration.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'desktop_click',
    displayName: 'Desktop Click',
    summary: 'Click at screen coordinates. Supports left/right/middle buttons and click count for double-click.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_type_text',
    displayName: 'Desktop Type Text',
    summary: 'Type text into the focused element. Optionally click at coordinates first. Long text (>160 chars) requires approval.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_press_keys',
    displayName: 'Desktop Press Keys',
    summary: 'Press a keyboard shortcut or key combination. Some shortcuts (Cmd+Q, Cmd+Space, etc.) are denied by policy.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_scroll',
    displayName: 'Desktop Scroll',
    summary: 'Scroll the screen at optional coordinates. Supports both vertical and horizontal scrolling.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_wait',
    displayName: 'Desktop Wait',
    summary: 'Wait for a specified duration (0-30000ms). Useful for letting UI animations complete.',
    lane: 'desktop',
    kind: 'control',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },

  // Terminal tools
  {
    canonicalName: 'terminal_exec',
    displayName: 'Terminal Exec',
    summary: 'Execute a shell command in the local terminal. Returns stdout, stderr, exit code, and timing. Always requires approval.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: true,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'terminal_get_state',
    displayName: 'Terminal Get State',
    summary: 'Read the current terminal runner state including effective cwd, last exit code, and last command summary.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'terminal_reset_state',
    displayName: 'Terminal Reset State',
    summary: 'Reset the terminal state. Clears accumulated command history and state.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },

  // Browser DOM tools (extension-based)
  {
    canonicalName: 'browser_dom_get_bridge_status',
    displayName: 'Browser DOM Get Bridge Status',
    summary: 'Inspect the browser DOM bridge connection status, including host, port, and whether the extension bridge is currently connected.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_get_active_tab',
    displayName: 'Browser DOM Get Active Tab',
    summary: 'Read the active browser tab metadata including title, URL, and bridge status through the extension surface.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_read_page',
    displayName: 'Browser DOM Read Page',
    summary: 'Read the DOM structure from all frames in the browser via the extension bridge. Returns interactive elements and page structure.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_find_elements',
    displayName: 'Browser DOM Find Elements',
    summary: 'Find elements in the browser DOM matching a selector or role. Returns matching elements with bounds and attributes.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_click',
    displayName: 'Browser DOM Click',
    summary: 'Click a browser DOM element selected through the extension bridge. Supports optional tab and frame targeting.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_read_input_value',
    displayName: 'Browser DOM Read Input Value',
    summary: 'Read the current value from an input-like browser DOM element matched by selector, tab, and frame scope.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_set_input_value',
    displayName: 'Browser DOM Set Input Value',
    summary: 'Set the value of a browser DOM input element through the extension bridge and return per-frame execution results.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_check_checkbox',
    displayName: 'Browser DOM Check Checkbox',
    summary: 'Set the checked state of a checkbox or toggle-like browser DOM control selected through the extension bridge.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_select_option',
    displayName: 'Browser DOM Select Option',
    summary: 'Select one or more options in a browser DOM <select> control and report the matching frame results.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_wait_for_element',
    displayName: 'Browser DOM Wait For Element',
    summary: 'Wait for a browser DOM element to appear or disappear without mutating the page.',
    lane: 'browser_dom',
    kind: 'control',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_get_element_attributes',
    displayName: 'Browser DOM Get Element Attributes',
    summary: 'Read browser DOM element attributes, state, and metadata for a selector within the active tab or a chosen frame.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_get_computed_styles',
    displayName: 'Browser DOM Get Computed Styles',
    summary: 'Read computed CSS styles for a browser DOM element matched by selector and optional frame scope.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_trigger_event',
    displayName: 'Browser DOM Trigger Event',
    summary: 'Dispatch a DOM event against a selected browser element with optional event type and event options payload.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },

  // Clipboard tools
  {
    canonicalName: 'clipboard_read_text',
    displayName: 'Clipboard Read Text',
    summary: 'Read text content from the system clipboard. Requires approval due to privacy sensitivity.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'clipboard_write_text',
    displayName: 'Clipboard Write Text',
    summary: 'Write text content to the system clipboard. Requires approval due to data sensitivity.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },

  // Secret/env tools
  {
    canonicalName: 'secret_read_env_value',
    displayName: 'Secret Read Env Value',
    summary: 'Read an environment variable value. Requires approval due to potential exposure of secrets.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: true,
    public: true,
  },

  // Workflow tools
  {
    canonicalName: 'desktop_list_pending_actions',
    displayName: 'Desktop List Pending Actions',
    summary: 'List pending approval actions waiting for an explicit accept or reject decision.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_approve_pending_action',
    displayName: 'Desktop Approve Pending Action',
    summary: 'Approve a pending action and let the runtime execute it through the normal audited path.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_reject_pending_action',
    displayName: 'Desktop Reject Pending Action',
    summary: 'Reject a pending action, record the outcome, and keep the approval queue in sync.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_get_session_trace',
    displayName: 'Desktop Get Session Trace',
    summary: 'Read recent session trace entries for audit, debugging, and workflow transparency.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_get_state',
    displayName: 'Desktop Get State',
    summary: 'Read the current run-level state including workflow progress, foreground context, and captured runtime state.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'workflow_open_workspace',
    displayName: 'Workflow Open Workspace',
    summary: 'Run the open-workspace workflow to reveal and focus a project in the configured IDE and file manager.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'workflow_validate_workspace',
    displayName: 'Workflow Validate Workspace',
    summary: 'Run the validate-workspace workflow to inspect changes and execute a validation command from the workspace root.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'workflow_run_tests',
    displayName: 'Workflow Run Tests',
    summary: 'Run the test workflow against a workspace and return the structured workflow result summary.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'workflow_inspect_failure',
    displayName: 'Workflow Inspect Failure',
    summary: 'Run the failure-inspection workflow to gather fresh diagnostics and summarize likely next steps.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'workflow_browse_and_act',
    displayName: 'Workflow Browse And Act',
    summary: 'Run a browser-oriented workflow that opens an app, optionally navigates to a URL, and performs a bounded action sequence.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'workflow_coding_loop',
    displayName: 'Workflow Coding Loop',
    summary: 'Run the bounded coding workflow that reviews, patches, and validates a targeted workspace change.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: true,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'workflow_coding_agentic_loop',
    displayName: 'Workflow Coding Agentic Loop',
    summary: 'Run the agentic coding workflow with bounded planning, patching, and validation over a targeted workspace task.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: true,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'workflow_resume',
    displayName: 'Workflow Resume',
    summary: 'Resume the currently suspended workflow after an approval or rejection decision.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
]

/**
 * Internal/test tools (not exposed to MCP clients by default)
 */
export const internalDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'desktop_open_test_target',
    displayName: 'Desktop Open Test Target',
    summary: 'Open a test target for development/testing purposes. Only available when test tools are enabled.',
    lane: 'internal',
    kind: 'internal',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: false,
  },
]

/**
 * Meta/directory tools
 */
export const metaDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'tool_directory',
    displayName: 'Tool Directory',
    summary: 'List available tools with optional filtering by lane, kind, or search query. Returns a compact directory for navigation and a structured list for programmatic access.',
    lane: 'internal',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
]
